name: Publish to GUN-ES to NPM

on:
  push:
    tags:
      - "v.*"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    env:
      NPM_CONFIG_PROVENANCE: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm i

      - name: Build the library
        run: npm run build

      - name: Check for NODE_AUTH_TOKEN
        run: |
          echo "Checking for NODE_AUTH_TOKEN environment variable..."
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "NODE_AUTH_TOKEN is not set!"
          else
            echo "NODE_AUTH_TOKEN is set (length: ${#NODE_AUTH_TOKEN})"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish gun-es
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Output npm debug log
        if: failure()
        run: cat /home/runner/.npm/_logs/*-debug-0.log
